### ISSUE TITLE
themeStyle issue

### ISSUE THREAD

**Issue by Gia777** [victoriadrake/hugo-theme-introduction#130]
Hi, I have the same issue as #122 themeStyle not working. I am using the theme via RStudio Blogdown on IOS and having trouble changing the themestyle to "dark". According to the #122 comment, I updated both RStudio and Hugo to make sure they are at the latest versions, but the dark themestyle still remain inactive. Does anyone else also have this issue? Can anyone provide more details about the solution? I really really like the dark style! Thanks in advance :)

**Comment by hanzei** [comment]
There shouldn't be more to do then changing `themeStyle` from `light` to `dark`.

What Hugo version are you running? What is the console output your see?

**Comment by Gia777** [comment]
Thank you for replying! It's a bummer...I'm running v0.54.0 version. Attached is the console output. 
<img width="824" alt="screen shot 2019-02-24 at 17 39 34" src="https://user-images.githubusercontent.com/46694666/53306485-96852b80-385b-11e9-895e-f4ac14df2011.png">

**Comment by hanzei** [comment]
You you please run `hugo version` and post the output here?

**Comment by Gia777** [comment]
Sure! but isn't blogdown::hugo_version() the code to check the installed Hugo version?

<img width="827" alt="screen shot 2019-02-25 at 12 48 05" src="https://user-images.githubusercontent.com/46694666/53357552-24185800-38fc-11e9-8dfd-4ec11e9d3d62.png">

**Comment by hanzei** [comment]
I have no idea what blogdown is. But a simple shell should do the tick here.

**Comment by Gia777** [comment]
Thanks so much! This is blogdown I referred to: [https://bookdown.org/yihui/blogdown/get-started.html](url) I've tried your suggestion and the output is still "error", but I'm pretty sure the hugo version I'm running is v0.54.0(the latest). I know nothing about sass--would it be possible for you to look at my dark style sass files and see if there is anything wrong or anything I can try tweaking? 

P.S. really appreciate your timely reply :) 

<img width="819" alt="screen shot 2019-02-25 at 19 19 27" src="https://user-images.githubusercontent.com/46694666/53378367-53968700-3933-11e9-9924-727d1fe433e5.png">

<img width="822" alt="screen shot 2019-02-25 at 19 27 46" src="https://user-images.githubusercontent.com/46694666/53378420-7fb20800-3933-11e9-913f-add14a314bdc.png">

**Comment by victoriadotdev** [comment]
Hey @Gia777,

Is your site generating properly with the light theme? If so, would you please post your config file, and/or the HTML page that is output?

Thank you.

**Comment by Gia777** [comment]
Hey! Thanks for replying :) 

Actually, my site doesn't generate properly with the light theme--the social media icons and the little arrow at the bottom of each section don't display anymore (they are replaced by empty squares instead). But this problem only popped up recently. 
<img width="1313" alt="Screen Shot 2019-03-31 at 23 13 15" src="https://user-images.githubusercontent.com/46694666/55301783-46762780-540c-11e9-8885-286a07774364.png">

Here is my config file: 
[config.toml.zip](https://github.com/victoriadotdev/hugo-theme-introduction/files/3027661/config.toml.zip)

<img width="1315" alt="Screen Shot 2019-03-31 at 23 02 48" src="https://user-images.githubusercontent.com/46694666/55301939-082d3800-540d-11e9-840f-659a09e0af84.png">

Thank you so much!!

**Comment by hanzei** [comment]
@Gia777 Would you mind uploading the source of your website on GH and linking it here? It would make debugging much easier.

**Comment by snow2k9** [comment]
Hey, if it's [this repo](https://github.com/Gia777/thankshanna), then I see no issues while hugo serving it.
But on [your Website](https://www.giawei.com/) your fonts are pulled from vickylai.com and getting a 404.

If i build your repo on my machine everything is alright.
Using Hugo Static Site Generator v0.54.0/extended linux/amd64

Perhaps you could try
`git submodule add https://github.com/victoriadotdev/hugo-theme-introduction themes/introduction`
Changing your config.toml `theme = "introduction"` and build your site again.

**Comment by hanzei** [comment]
Hey @snow2k9,

I've build your website locally and it works just fine. Can you explain in more details what the problem is?

**Comment by hanzei** [comment]
Hey @snow2k9,

I've build your website locally and it works just fine. Can you explain in more details what the problem is?

![Screenshot from 2019-08-07 16-09-35](https://user-images.githubusercontent.com/16541325/62629645-e0575f00-b92d-11e9-8a03-1f04a2643ffb.png)

**Comment by snow2k9** [comment]
Not me, tried to help :)

@Gia777

**Comment by hanzei** [comment]
Oh, woops mixed up the names :wink:

**Comment by Gia777** [comment]
Thank you so much, everyone! I appreciate your help :^) I've decided to build a new website due to a time limit, but I'll def check back on this theme when I have more free time. My absolute favorite theme--keep up the good work!!
