### ISSUE TITLE
Image display enhancement

### ISSUE THREAD

**Issue by mingsu** [victoriadrake/hugo-theme-introduction#131]
Image ratio
============

Images with non-standard size (e.g. large height but small width) are filled in projects image blocks, which changed the ratio.

How to keep the original ratio?

Image rotation
============

Is it possible to automatic read the rotation property from exif, so that to get the right rotation.

Something like:

```
img {
    image-orientation: from-image;
}
```

I tried to add this css to `assets/custom.css`, but with no success.

Just minute ago, I found the wrong rotation is caused by the **resize process**. So it is necessary to get the right rotation property after resize the images.

**Comment by hanzei** [comment]
@mingsu Can you please share a screenshot and a sample image?
