### ISSUE TITLE
Problem with integrity attribute when using as submodule

### ISSUE THREAD

**Issue by nsio-admin** [victoriadrake/hugo-theme-introduction#142]
When attempting to deploy a site using Hugo + Introduction theme (configured as a submodule) using Azure Repos and Azure Pipelines, and then deploying to an Azure App Service website, I keep getting the following error in the browser from the finally deployed site:

Failed to find a valid digest in the 'integrity' attribute for resource 'https://mysite.azurewebsites.net/css/main.min.9c369cba081a2d79f73412598fd8805180fbeb46cbd964287150e9a3074143c9.css' with computed SHA-256 integrity 'VSqxe9wiXvf5axI8/SigZplDZ+aWLq3SvJV0qVriU1M='. The resource has been blocked.
 
Not sure if this problem is specific to this set of components on Azure but I suspect it relates to different CR/LF handling when the submodule is fetched and then the site is built.  I wonder if there is a way to address this by means of entries in the .gitattributes file (along the lines of https://help.github.com/en/articles/dealing-with-line-endings)?

Many thanks in advance.

**Comment by hanzei** [comment]
I'm quite sure that has nothing to do with submodules.

Would you mind trying the extended hugo version for the build script/environment?

**Comment by hanzei** [comment]
Where does the code use CRLF?

**Comment by hanzei** [comment]
Closing this one use to inactivity. Let me know if this is still an issue @nsio-admin
