### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by master2go** [victoriadrake/hugo-theme-introduction#164]
Hello,
i'm new to Hugo and like introduction very much. Is there a possibility to insert a logo?
Thanks a lot
Inge

**Comment by hanzei** [comment]
Hey @master2go,

You add images to the sections on the home page 
![Screenshot from 2019-08-09 07-09-56](https://user-images.githubusercontent.com/16541325/62755616-089da580-ba75-11e9-9be8-84b683392318.png)

Does this solve your question?

**Comment by Athanasiamo** [comment]
I have a solution for adding logos to the hero (behind the text) which I was working on adding as a contribution, if it is of interest, I can try speed that a long a little

**Comment by Athanasiamo** [comment]
I've done a PR for a solution I have for using logo in this theme, (#188)
