### ISSUE TITLE
Dark Theme not working

### ISSUE THREAD

**Issue by SiddAjriY2Jaccount** [victoriadrake/hugo-theme-introduction#179]
Changing theme param to dark in config.toml is not changing the theme

**Comment by hanzei** [comment]
What Hugo version are you using?

**Comment by SiddAjriY2Jaccount** [comment]
> What Hugo version are you using?

v0.50

**Comment by hanzei** [comment]
Can you please show the output of `$ hugo version`?

**Comment by SiddAjriY2Jaccount** [comment]
Sure
$ hugo version
Hugo Static Site Generator v0.50 linux/amd64 BuildDate: 2018-10-29T09:52:34Z

**Comment by hanzei** [comment]
Would you please install the extended version of Hugo? https://gohugo.io/getting-started/installing/

**Comment by SiddAjriY2Jaccount** [comment]
Install it again? As there is no update command available, iirc

**Comment by hanzei** [comment]
Yes, you have to deinstall your old hugo version and install the extended one.

**Comment by SiddAjriY2Jaccount** [comment]
What is the latest version? I have reinstalled (using apt-get) and now the version is v0.40.1

**Comment by SiddAjriY2Jaccount** [comment]
I've done so for v0.58.0, the dark theme and favicon still will not update

**Comment by hanzei** [comment]
Can you please share the output of `$ hugo version` with me? Can run your hugo build with `-v`?

**Comment by SiddAjriY2Jaccount** [comment]
Running the Build with -v didn't change the rendered website.

$hugo version
Hugo Static Site Generator v0.58.0-64D8BF1E linux/amd64 BuildDate: 2019-09-04T15:43:47Z

**Comment by SiddAjriY2Jaccount** [comment]
Another issue that has arisen upon re-installation of Hugo is that clicking on images or highlighted text in projects section doesn't render the text box with the project details.

**Comment by hanzei** [comment]
> Running the Build with -v didn't change the rendered website.
> 
> $hugo version
> Hugo Static Site Generator v0.58.0-64D8BF1E linux/amd64 BuildDate: 2019-09-04T15:43:47Z

Your are still not using the extended version. The output should be: 
```$ hugo version
Hugo Static Site Generator v0.57.2/extended linux/amd64
```

**Comment by hanzei** [comment]
> Another issue that has arisen upon re-installation of Hugo is that clicking on images or highlighted text in projects section doesn't render the text box with the project details.

Please open a new issue for this

**Comment by SiddAjriY2Jaccount** [comment]
> > Running the Build with -v didn't change the rendered website.
> > $hugo version
> > Hugo Static Site Generator v0.58.0-64D8BF1E linux/amd64 BuildDate: 2019-09-04T15:43:47Z
> 
> Your are still not using the extended version. The output should be:
> 
> ```
> Hugo Static Site Generator v0.57.2/extended linux/amd64
> ```

Oh alright, will try it out and let you know.

**Comment by SiddAjriY2Jaccount** [comment]
Unable to install extended version of Hugo on Linux Mint. Docs say apt-get installs the extended version, but it has not proven to be the case.

**Comment by SiddAjriY2Jaccount** [comment]
Installing using snap resolves the issue, thank you for the help!
