### ISSUE TITLE
Adding files like pdf or doc files

### ISSUE THREAD

**Issue by SiddAjriY2Jaccount** [victoriadrake/hugo-theme-introduction#180]

**Comment by hanzei** [comment]
Can you please enaborate a bit more? What exactly is you feature request?

**Comment by SiddAjriY2Jaccount** [comment]
> Can you please enaborate a bit more? What exactly is you feature request?

I'm not able to figure out how to upload files to host on the webpage. Do I have to add it as a Google Drive Link or can it be hosted on the site itself?

**Comment by hanzei** [comment]
Hugo allows the inclusion of static files. Please see https://gohugo.io/content-management/page-bundles/ for guidance.
