### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by ujwal-narayan** [victoriadrake/hugo-theme-introduction#182]
Hi,
Font awesome icon loads fines in the local server, but whenever I deploy it on aws amplify it attempts to load from `www.example.org` folder instead of the domain name, even though the domain is correctly specified in the config file. 
i've tried modifying the sass file for the font awesome loading but have not had any luck getting it to work so far, 
It loads perfectly fine on the local server, but  when deployed it attempts to load from `www.example.org`

Any help is appreciated, thanks!

**Comment by victoriadrake** [comment]
HI! I would guess it's something to do with your deploy process, as there's no "`www.example.org`" anywhere in the theme. Even the exampleSite `config.toml` is "`example.com`", but as you said, your config should be correct.

I can help troubleshoot given more details on your deploy process. Are there separate configuration settings for Amplify that may be interfering?

**Comment by ujwal-narayan** [comment]
Hi,
Yeah it seems to be a deployment issue. Fiddled around more and it's a CORS not enabled problem. 
Thanks for your help!
