### ISSUE TITLE
Demo page is broken

### ISSUE THREAD

**Issue by awhitford** [victoriadrake/hugo-theme-introduction#185]
The [Demo](https://themes.gohugo.io/theme/hugo-theme-introduction/) link from [here](https://themes.gohugo.io/hugo-theme-introduction/) is _broken_ --  it appears that the font loads are returning 404. 😢 
```
NunitoSans-Regular.ttf:1 Failed to load resource: the server responded with a status of 404 ()
fa-brands-400.woff2:1 Failed to load resource: the server responded with a status of 404 ()
fa-solid-900.woff2:1 Failed to load resource: the server responded with a status of 404 ()
fa-brands-400.woff:1 Failed to load resource: the server responded with a status of 404 ()
fa-solid-900.woff:1 Failed to load resource: the server responded with a status of 404 ()
fa-brands-400.ttf:1 Failed to load resource: the server responded with a status of 404 ()
fa-solid-900.ttf:1 Failed to load resource: the server responded with a status of 404 ()
```

**Comment by wireshark47** [comment]
Hi @awhitford  The issue exists in the demo link from the Hugo website, but won't be present in the Netlify hosted version of the same. Refer [this](https://github.com/victoriadrake/hugo-theme-introduction/issues/184) if you face the same problem when hosting it on your own.

**Comment by awhitford** [comment]
@wireshark47 Thanks for the tip.
