### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute

### ISSUE THREAD

**Issue by AIRyndon** [victoriadrake/hugo-theme-introduction#187]
Hello Everyone

I just started using this theme, and when I publish to github pages I get this error:

**Failed to find a valid digest in the 'integrity' attribute for resource:**

The four culprit files are these: 
![image](https://user-images.githubusercontent.com/8405286/68974695-3a818d80-0856-11ea-9f03-792e8977b596.png)

I read about the line ending fix [here][1] and added these to the gitattributes in the themes folder, and in the site's own folder as well:
```
* text=auto
*.html text eol=lf
*.js text eol=lf
*.css text eol=lf
*.jpg binary
*.png binary
```
I removed the introduction theme as a submodule, and just copied it over directly - I still have the same issue however. My public folder is also a submodule, but I'm thinking that isn't the issue. In local development the problem does not exist. I'm stuck in this issue for a day now, and help is much appreciated :)

Thanks in advance!

[1]: https://github.com/victoriadrake/hugo-theme-introduction/issues/142

**Comment by AIRyndon** [comment]
I did a hack and removed the values for integrity in their respective files, the error is resolved now but I think there could be a better solution to this issue.

**Comment by victoriadrake** [comment]
Hi! Can you clarify your process for "publishing to github pages"? Where do you see the error?

**Comment by AIRyndon** [comment]
Hello! If I remember correctly, the error pops up on the homepage area - the modals of the projects don't popup.

Because this is my first time using Hugo, I believe I just followed the instructions [here](https://gohugo.io/hosting-and-deployment/hosting-on-github/#github-user-or-organization-pages) to publish to github pages - used a User page I think.  

Oh thank you for the awesome work :)

**Comment by ddean6232** [comment]
same error on two different browsers (FireFox and Chrome) with the "integrity" issue.  I have deployed to Firebase hosting the basic site example.  Any further information on a fix?

**Comment by ddean6232** [comment]
> I did a hack and removed the values for integrity in their respective html files, the error is resolved now but I think there could be a better solution to this issue.

what files did you hack?

**Comment by AIRyndon** [comment]
@ddean6232 its been awhile now so I have forgotten it. Most likely its those four files on my first post, I remember I just looked at the files that were causing the error from Chrome dev tools

**Comment by SachinPendse** [comment]
Did that work for you @ddean6232? What exactly did you hack in those files @AIRyndon? The JavaScript/CSS in them is quite daunting! Thanks all!

**Comment by ddean6232** [comment]
@SachinPendse I abandon this project. If the developer can't even get involved then its not worth the time. I have labelled it dead code.

**Comment by victoriadrake** [comment]
I’ve not been able to reproduce the issue to provide a quick answer. If others are experiencing this, would you please confirm that you’ve followed the [Getting started](https://github.com/victoriadrake/hugo-theme-introduction#get-the-theme) instructions in the README, and are using extended Hugo? (Run `hugo version` to find out.)

If you wish to work around the [subresource integrity](https://gohugo.io/hugo-pipes/fingerprint/) feature in the meantime, you may remove it in the file `layouts/partials/head/css.html`:

1. Remove `| fingerprint ` from line 10
2. Remove ` integrity="{{ $bundle.Data.Integrity }}"` from lines 11 and 17.

Resulting in:

```html
{{ $bundleRaw := resources.Get "sass/style.sass" | resources.ExecuteAsTemplate "css/main.tmp.css" . }}

{{ if .Site.IsServer }}
{{ $cssOpts := (dict "targetPath" "css/main.css" "enableSourceMap" true ) }}
{{ $bundle := $bundleRaw | toCSS $cssOpts }}
<link rel="stylesheet" href="{{ $bundle.RelPermalink }}" media="screen">
{{ else }}
{{ $cssOpts := (dict "targetPath" "css/main.css" ) }}
{{ $postCSSOpts := (dict "use" "autoprefixer" ) }}
{{ $bundle := $bundleRaw | toCSS $cssOpts | postCSS $postCSSOpts | minify }}
<link rel="stylesheet" href="{{ $bundle.RelPermalink }}" crossorigin="anonymous" media="screen">
{{ end }}

<!-- Custom css -->
{{ range .Site.Params.customCSS -}}
    {{ $style := resources.Get . }}
    <link rel="stylesheet" href="{{ $style.RelPermalink }}" crossorigin="anonymous" media="screen">
{{- end }} 
```
