### ISSUE TITLE
Theme demo broken on the Hugo Themes website

### ISSUE THREAD

**Issue by onedrawingperday** [victoriadrake/hugo-theme-introduction#196]
Hello again @victoriadrake 

Just like the Call Me Sam theme this theme's demo is also broken on the Hugo Themes website due to https://github.com/gohugoio/hugo/issues/7036

To fix please regenerate and commit the theme's resources.

Once you do this feel free to close this issue and then I will update the theme on the Hugo Themes repo.

Thanks.

**Comment by victoriadrake** [comment]
Done! Thank you @onedrawingperday
