### ISSUE TITLE
Change from /blog/ to /post/

### ISSUE THREAD

**Issue by Mattyfaz** [victoriadrake/hugo-theme-introduction#202]
Hey!
First of all, I love the theme!

I am trying to transition an old Hugo site to this this theme however the old theme used _/post/_ for blog posts, whereas introduction uses _/blog/_.

Is there anyway to modify introduction to use _/post/_? 

If I switch over using _/blog/_ any link to my site out on the web will break, causing a pretty negative impact with SEO.

![Screen Shot 2020-04-21 at 4 11 37 pm](https://user-images.githubusercontent.com/10377148/79831450-c93c9c80-83ea-11ea-8a39-49143ae9ff24.png)

If not I understand, I will have to deal with it. 
Just wanted to check if there was any easy way to perform this functionality.

Thank you!

**Comment by victoriadrake** [comment]
Hi there! I'm glad you like the theme!

You can change the URL of your content using [Hugo's permalinks config setting](https://gohugo.io/content-management/urls/#permalinks). To change `blog/` to `post/`, put all your `post` content in the `blog` folder, then add this setting to your `config.toml` (or `.yaml`, or `.json`):

```toml
[permalinks]
  blog = "/post/:title/"
```

This would tell Hugo to build your content at `example.com/post/awesome-post-title/`, for instance. You can configure the URL in further ways, such as using dates, by referring to the documentation.
