### ISSUE TITLE
Please remove device mockups from theme screenshots

### ISSUE THREAD

**Issue by onedrawingperday** [victoriadrake/hugo-theme-introduction#204]
Hello, 

Recently the Hugo Themes submission guidelines were updated with the following:

> Screenshots are used as theme previews in the list, they should feature a theme's layout (without any browser chrome or device mockups)

I kindly request that you remove the device mockups. The list is supposed to illustrate the layout of a theme. The mockups do not look particularly good on mobile.

Please let me know once you do the above.

cc: @digitalcraftsman

**Comment by victoriadrake** [comment]
All set!
