### ISSUE TITLE
CSS build issues

### ISSUE THREAD

**Issue by stephenplatz** [victoriadrake/hugo-theme-introduction#210]
I thought I'd open an issue here, although I'm not sure if this could actually be related to https://github.com/gohugoio/hugo/issues/7278#issue-618943431. In any case, I'm still getting the `POSTCSS: failed to transform "css/main.css"` error when I try to build the site, despite making sure all of the dependencies in the documentation are installed.

I'm not actually using a snap installation of Hugo, though `Hugo Static Site Generator v0.71.1-A301F6B2/extended linux/amd64 BuildDate: 2020-05-25T09:18:12Z`

**Comment by gray419** [comment]
I'm getting this error also. I've created a new hugo site and added this theme as a submodule. I'm able to serve locally, but not able to build.

My environment:
- node v12.18.1
- Hugo Static Site Generator v0.72.0/extended darwin/amd64 BuildDate: unknown

```
Error: Error building site: POSTCSS: failed to transform "css/main.css" (text/css): resource "sass/sass/style.sass_b1195a7e151e6f4379f823b1b2b4f87a" not found in file cache
```

**Comment by gray419** [comment]
Ok nvm I was able to fix this by reading this [post](https://discourse.gohugo.io/t/postcss-transform-error/24929/2). I ran these two commands and I was able to build:

`sudo npm i -g postcss-cli`
`sudo npm i -g autoprefixer `

**Comment by victoriadrake** [comment]
Thank you for sharing @gray419!

**Comment by eauchat** [comment]
Hello, I'm having the same issue, using the theme via gitlab-ci.
Would anyone have a suggestion on how the issue could be solved in that context. I don't know if the solution proposed by @gray419 can be applied in such docker environment.

**Comment by mike-foucault** [comment]
@eauchat , I fixed the same issue by adding a package.json file, with the following content :
`{
  "name": "netlify-deps",
  "version": "0.1.0",
  "dependencies": {
    "postcss-cli": "7.1.1",
    "autoprefixer": "9.8.4"
  }
}
`

I did not try with gitlab-ci, I use netlify. By default, Netlify runs npm install to install the dependencies listed in my package.json file. So, if you configure your CI to install the dependencies, the issue will be solved.

**Comment by dannie-ml** [comment]
i've already done all your solutions and not worked for me ;(

**Comment by victoriadrake** [comment]
> i've already done all your solutions and not worked for me ;(

@dannie-ml If you provide some error feedback, information about your set up, or a link to your site repository, we can try and help! 😄

**Comment by nuts7** [comment]
> Ok nvm I was able to fix this by reading this [post](https://discourse.gohugo.io/t/postcss-transform-error/24929/2). I ran these two commands and I was able to build:
> 
> `sudo npm i -g postcss-cli` `sudo npm i -g autoprefixer `

After solving this problem, I have a new problem during the build 😄

```
sudo hugo
Start building sites …
Total in 723 ms
Error: Error building site: POSTCSS: failed to transform "css/main.css" (text/css): /usr/local/lib/node_modules/postcss-cli/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/postcss-cli/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

`Linux site-cat 5.10.0-19-cloud-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux`
`Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: 2021-07-18T09:31:51Z (debian 0.80.0-6+b5)`
```
{
  npm: '7.5.2',
  node: '12.22.12',
  v8: '7.8.279.23-node.57',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '72',
  nghttp2: '1.43.0',
  napi: '8',
  llhttp: '2.1.4',
  http_parser: '2.9.4',
  openssl: '1.1.1n',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
```

**Comment by DuaneOBrien** [comment]
For folks who find this issue because they are still tripping over the error:

`POSTCSS: failed to transform "css/main.css"`

I added the package.json shown in [this comment](https://github.com/victoriadrake/hugo-theme-introduction/issues/210#issuecomment-651869483) and I still had the error, because I forgot to run:

`npm install`

This cleared the error for me.
