### ISSUE TITLE
Feature request: dark\light user switch

### ISSUE THREAD

**Issue by Ckln** [victoriadrake/hugo-theme-introduction#211]
Hey there,

Thanks for theme I really appreciate it,
I do not know much about css and sass or less or anythings related to CSS.

But I was wonder if there is any plan going on for enable the user to being able to switch on the fly dark and light them ?

**Comment by victoriadrake** [comment]
Hello! I’m glad you like the theme!

I’m not building this feature at the moment, but it’s a great suggestion and contributions are always welcome!
