### ISSUE TITLE
Vertical Images are stretched in the preview

### ISSUE THREAD

**Issue by mijorus** [victoriadrake/hugo-theme-introduction#212]
And you cant scroll once you open them

**Comment by victoriadrake** [comment]
Hi there. Could you be more specific about where this is happening? I’m not seeing what you’re seeing.

**Comment by mijorus** [comment]
sorry, yesterday I didn't explain the problem properly.

When you upload a picture in the projects which is not 3 by 2, the thumbnail gets stretched and, if the image is vertical, once I open the project It does not allow me to scroll (it zooms in to the top-part of the pic).

Using the inspector I found there are some CSS classes for more ratios that will fix the stretched previews, but I couldn't fix the latter

![image](https://user-images.githubusercontent.com/39067225/84121857-f1826800-aa37-11ea-8813-f93f0203b555.png)

**Comment by mijorus** [comment]
![image](https://user-images.githubusercontent.com/39067225/84122479-c6e4df00-aa38-11ea-8de6-2f3011007501.png)

This is an example of the zoomed-in picture I was also talking about. The image is higher than the viewport but it does not allow me to scroll. Although there is a description below, on a 16:9 display I cant scroll down to read it

**Comment by victoriadrake** [comment]
Closed by #214

**Comment by JoGaertner** [comment]
Hey,
I still can't scroll, when I have vertical Images in the Projects. Any Ideas?
Thanks

**Comment by mijorus** [comment]
Set the overscroll property to `auto` or `scroll`
