### ISSUE TITLE
Using Font Awesome in content

### ISSUE THREAD

**Issue by DanielHouston** [victoriadrake/hugo-theme-introduction#217]
Firstly, thank you for an awesome theme. 
I'm (very) new to Hugo and not skilled at web development, but from what I can make out Font Awesome is included within the theme as it's used for the social partial, right? 
Is there a way I can reuse the same Font Awesome svgs within the content of posts? I have tried to create a shortcode which expands to a span, but wasn't able to get it to appear within the body of a post.

(Sorry if this is a very simple question!)

**Comment by victoriadrake** [comment]
Hi there @DanielHouston! Worry not, all questions are welcome. :)

Font Awesome free is bundled, yes. Here's how to use the icons: https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

To ensure Hugo renders the HTML that Font Awesome uses in posts, make sure these lines are in your `config.toml`:

```toml
[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true
```

If your shortcode renders HTML, that may be your missing piece! Please do let me know how it goes.

**Comment by DanielHouston** [comment]
Fantastic! That worked exactly as expected after the `config.toml` additions. Thanks!

**Comment by victoriadrake** [comment]
You're welcome!
