### ISSUE TITLE
HTML tags in the title

### ISSUE THREAD

**Issue by christian-heusel** [victoriadrake/hugo-theme-introduction#219]
Hey, let me start off by thanking for this awesome HUGO theme! :heart: 

##   :exclamation: The Problem :exclamation: 
If you have a title using markdown (i.e. "_Long_ forum post") This renders to 
```html
<title>
&lt;em&gt;Long&lt;/em&gt; Form Post - My Website
</title>
```
Would it be possible to strip that off?

Cheers,
Chris

**Comment by victoriadrake** [comment]
Hello Chris! You're welcome.

It's not possible to have the post page render the formatting without the HTML. Do you mean to ask about stripping it in another place?

**Comment by christian-heusel** [comment]
I mean yeah, this looks right:
![image](https://user-images.githubusercontent.com/26827864/85303184-75156d80-b4aa-11ea-972f-a165aad622a2.png)
But this does not really look like wanted behavior in my opinion
![image](https://user-images.githubusercontent.com/26827864/85303269-8d858800-b4aa-11ea-924a-fc5650da440e.png)

**Comment by victoriadrake** [comment]
Ah, I see what you mean now. The HTML tags are showing up in the page title.

I'll change the page title to not render Markdown to HTML tags, however, I think you'll still see the Markdown formatting:

![Screenshot_20200622_115813](https://user-images.githubusercontent.com/24644237/85314968-3e2e6000-b488-11ea-93fd-5ae633f416c5.png)

I'll have to think about how I could remove that without accidentally stripping intended non-alphanumeric characters from titles.
