### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by iLikeHajk** [victoriadrake/hugo-theme-introduction#221]
Hello!

Thanks for a great theme. In accordance with your guidlines I'm starting with an issue. I've done a Swedish version of the .toml-file in /i18n/. A PR will follow. I hope I do this right, it's my first contribution to anything on GitHub ever. :)

Regards,
Eriq

**Comment by victoriadrake** [comment]
Hello Eriq! Thank you very much for the translation, and I'm flattered you picked this project for your first contribution! 😄 Welcome to the wonderful world of open source!
