### ISSUE TITLE
No content on netlify

### ISSUE THREAD

**Issue by tonitassimo** [victoriadrake/hugo-theme-introduction#223]
Hey there :)

First of all I want to thank you for your theme! I just tried it and it works great on my machine.
![localhost](https://user-images.githubusercontent.com/29860675/87307153-65250280-c519-11ea-92f5-1c3daae18a8e.png)
I then tried to deploy the initial site to netlify, which is connected to my github account. It says that no errors occured and the site got published. However there is (nearly) no content on the published site.
![netlify](https://user-images.githubusercontent.com/29860675/87307938-c00b2980-c51a-11ea-83b3-6f0f811c9d0e.png)
I'm not sure whether or not this is a problem with the theme - probably not :D I already tried adding a netlify.toml file, which didn't work either. Maybe you have some ideas what I could try or need to take care of when deploying the site to netlify.

**Comment by tonitassimo** [comment]
Nevermind. Was my own fault! :)

**Comment by victoriadrake** [comment]
Glad you got it figured out! 😁

**Comment by rockrgrrl** [comment]
@tonitassimo I had a similar issue. How did you fix it?
