### ISSUE TITLE
Typo: "Project" vs "Projects" in menu

### ISSUE THREAD

**Issue by henrylu93** [victoriadrake/hugo-theme-introduction#224]
Using the default menu, the main page shows "Projects" in the menu. If I navigate to /blog/, the menu shows "Project" without the s. Can this be changed to display "Projects" consistently? Thanks very much to Victoria and other contributors for this theme.

**Comment by thegreatluke** [comment]
I sent a pr that I *think* fixes this issue. I'm still learning my way around all the in's and out's of how this works.

**Comment by victoriadrake** [comment]
Closed in #241. Thank you @thegreatluke!
