### ISSUE TITLE
Unable to customize layouts

### ISSUE THREAD

**Issue by linhtto** [victoriadrake/hugo-theme-introduction#225]
I copied the folder `/themes/introduction/layouts` to the root folder and edited it with no effect. Editing directly within the theme works. 

Given that Hugo allows this type of customization, I'm wondering what's going on?

**Comment by victoriadrake** [comment]
Hi @linhtto! Thank you for posting this well-written issue!

I was not able to reproduce the problem when I created my own custom layouts directory in the site root. Here's what the site directory structure looks like:

```sh
site_root/
├── config.toml
├── content
│   ├── de
│   ├── en
│   └── es
├── layouts
│   ├── index.html <-------- customized file
│   └── shortcodes
│       ├── md.html
│       └── readfile.html
└── static
    └── img
```

Would you confirm if this matches yours?

**Comment by linhtto** [comment]
Thanks! I'm not sure how but it's working for me now. Sorry for the false alarm.

**Comment by victoriadrake** [comment]
No worries! I’m glad to hear it!
