### ISSUE TITLE
Allow for content to use markdown with HTML5?

### ISSUE THREAD

**Issue by linhtto** [victoriadrake/hugo-theme-introduction#226]
I'm particularly interested in the feature where you can add [collapsible content](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d).

Is this possible? Thanks!

**Comment by linhtto** [comment]
To answer my own question:

- To add HTML directly, one needs to change `config.toml` to add

```
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```
- The alternative option is to use shortcodes. However, I once again cannot just add shortcuts to `/layouts/shortcodes` in my own directory (as instructed by [Hugo](https://gohugo.io/templates/shortcode-templates/)) and I'll have to modify the themes folder directly (in `layouts/shortcodes`). This problem is related to the other issue I opened.

**Comment by victoriadrake** [comment]
Thank you for posting the answer, @linhtto! I'm adding a post to the exampleSite to hopefully make this clearer. I'll respond to your other issue separately.
