### ISSUE TITLE
Small clean up of extra fonts and unused variable

### ISSUE THREAD

**Issue by linhtto** [victoriadrake/hugo-theme-introduction#229]
I can work on a small Pull Request for the following small clean-ups if that's okay:
 
- The FA fonts in the outer `/static/fonts` folder are unused (the versions that are actually used are in `/static/fonts/fontawesome-free`).

- The base variable `$title-weight` in `/assets/sass/_base_variables.sass` is unused. I believe it's meant to be used in `/assets/sass/_base.sass` to change the font-weight of the title. This is currently hard-coded, and it's why the `$title-weight` variable is redundant.

- Optional: The variable `$family-monospace` seems undefined so it looks like the default available monospace font will be used? Is this intentional?

**Comment by victoriadrake** [comment]
That would be great! Thank you!

The two base variables you mentioned should be used. Would you put them into use in the appropriate places? Yes, `$title-weight` is meant to be the font-weight for titles.

`$family-monospace` is supposed to be a monospace font. The default available one is fine, or if you have one you'd like to bundle I'd be up for that suggestion.

**Comment by linhtto** [comment]
I submitted the Pull Request. While I was at it, I upgraded Bulma as I would like to use some of their new variables. Thanks!
