### ISSUE TITLE
Using custom local/Google fonts

### ISSUE THREAD

**Issue by haban3ra** [victoriadrake/hugo-theme-introduction#234]
Hi! I don't know if this is the right place to ask for help but I wanted to use custom fonts either by local or Google fonts. 
How should I change it? 
I have tried installing the font locally in the `static` > `fonts` folder and modifying the SASS `_fonts` file from the ` assets` folder but I can't seem to make it work. Ideally, I just wanted to change the font for the body but leave the original font for the headings which is Nunito Sans.

Any idea how to fix it? Thank you.

**Comment by linhtto** [comment]
You also need to change the variables in `_base-variables.sass`.
