### ISSUE TITLE
Adding authors and multi-authors to blog posts

### ISSUE THREAD

**Issue by beetlejuicegalactica** [victoriadrake/hugo-theme-introduction#235]
I'm having a hard time adding authors/multi-authors on my blog posts.  I've created an `_index.md` on the `authors` folder on `content `and added `author` taxonomy on `config.toml`. Also, I want to create a dedicated page for each author that lists all their articles. 
This is my first time using Hugo, I'm sorry.
What to do next? Help?

**Comment by victoriadrake** [comment]
Can you be a bit more specific about what you're seeing and how that differs from what you expect to see?

Creating the file with path `content/authors/_index.md` will create a section in your site with the URL `http://example.com/authors/`. You'll want to ensure there is [front matter](https://gohugo.io/content-management/front-matter#readout) in `_index.md` and that one of the lines is `draft: false`.

If you're using `authors` as a taxonomy, you should be able to see a page that lists all their posts at `https://example.com/authors/name/`. It'll be a taxonomy list page. See [Lists of Content in Hugo](https://gohugo.io/templates/lists/).
