### ISSUE TITLE
Taxonomies ignored in blog post pages

### ISSUE THREAD

**Issue by victoriadrake** [victoriadrake/hugo-theme-introduction#236]
Potentially related to #235, it does not appear that the `single.html` page template for blog posts will display taxonomy names that aren't `tags`:

https://github.com/victoriadrake/hugo-theme-introduction/blob/2263cdb0fa5664393f192d872c1d1f6196c6d684/layouts/blog/single.html#L45

Hugo supports any [user-defined taxonomy](https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy). The theme should be updated to display these, regardless of what they are named.

I think these are the appropriate docs: [Taxonomy Templates](https://gohugo.io/templates/taxonomy-templates/#render-a-sites-taxonomies)

**Comment by thegreatluke** [comment]
I'll take a look at this one. Do I have to do anything specific (other than comment) to let others know someone is working on this?

**Comment by victoriadrake** [comment]
Nope, all good! Thank you for taking a look!

**Comment by thegreatluke** [comment]
Created PR #248
