### ISSUE TITLE
How to add additional blog summaries to the home page?

### ISSUE THREAD

**Issue by thegreatluke** [victoriadrake/hugo-theme-introduction#237]
I'm trying to figure out how to add additional blog summaries to the home page.

I copied the theme's "list.html" to my site_root/layouts/blog/list.html" and edited the line:
`{{ range first 1 .Pages.ByPublishDate.Reverse }}`
to `{{ range first 3 .Pages.ByPublishDate.Reverse }}`

My thought was that would tell hugo to loop through the first 3 posts...? But that doesn't seem to work.

Any suggestions would be appreciated.

**Comment by thegreatluke** [comment]
Ok so making that change sort of emphasized the first 3 posts on the "blog" page - That's ok. 

I added the same file to my layouts/home thinking that would do the trick... but nope.

**Comment by thegreatluke** [comment]
Ok - So I apologize for opening this so quickly and then figuring it out on my own... 

Here is what you have to do in case anyone else is curious - 

create a directory 

/my_site/layouts/partials/home

Add blog.html to that directory

make the edit to the range line that I listed above.

Sorry for opening an easy issue. :)

**Comment by victoriadrake** [comment]
I’m glad you figured it out, Luke!

If anyone wants to submit a PR for a configurable number of blog summaries on the home page, I’d be open to that idea! 👍

**Comment by thegreatluke** [comment]
I’m very new to hugo and static site generators in general but I’ll take a shot at it.
