### ISSUE TITLE
project preview not showing

### ISSUE THREAD

**Issue by irhuru** [victoriadrake/hugo-theme-introduction#245]
Hi! 

I have created a personal website and I have an issue with the "projects" section: 

When I go to my list of projects in the main page, the project preview doesn't open. This means that in order to read the description of a project, my only option is to click on "all projects" and then open the project from there. 

The thing is that this works perfectly fine when I use `hugo server` from my terminal. However, it doesn't work when I render my site and I don't know why... This is the link to my site, in case you want to take a look: https://irhuru.github.io/ 

I'm currently using MacOS (version 10.15.4) and Google Chrome, though I have tried with Safari as well and I still have the same problem.

**Comment by victoriadrake** [comment]
Hi Irati! When I visit your site I see this in the console:

```txt
Mixed Content: The page at 'https://irhuru.github.io/' was loaded over HTTPS, but requested an insecure script 
'http://irhuru.github.io/js/bundleOwlCarousel.afccb66….js'. This request has been blocked; the content must be 
served over HTTPS.
```

How are you configuring your site address? Does your `config.toml` file have `https://` in the `baseURL`?

**Comment by irhuru** [comment]
I just realized there was a typo in that file!

Thanks 👍🏼

**Comment by victoriadrake** [comment]
You're welcome! Glad you got it sorted out.
