### ISSUE TITLE
Remove Google Plus Share Buttons.

### ISSUE THREAD

**Issue by thegreatluke** [victoriadrake/hugo-theme-introduction#249]
Google plus has been shut down, we should remove the share buttons from the theme.

**Comment by thegreatluke** [comment]
I think I know all the places in the project to remove Google Plus if you want me to go ahead with this.

**Comment by victoriadrake** [comment]
Please feel free! Thank you again!

**Comment by victoriadrake** [comment]
We should still do this.

**Comment by victoriadrake** [comment]
@thegreatluke Are you still interested in tackling this one?
