### ISSUE TITLE
image transformation

### ISSUE THREAD

**Issue by timpauli** [victoriadrake/hugo-theme-introduction#250]
Hi,
first of all thanks for working on this theme!

The image one uses in the about section gets transformed.
It gets rescaled and the quality drops to 75 percent I think.
Is it possible to influence this process?
Because for my taste the quality gets sometimes a bit too bad.

Thank you very much.

**Comment by victoriadrake** [comment]
Hello Tim!

Yes, you can change this behavior. The image is transformed by the [Resize image processing](https://gohugo.io/content-management/image-processing/#resize) on line 75 of the `index.html` template file:

https://github.com/victoriadrake/hugo-theme-introduction/blob/193dc1a0d39afe05710ae5843ef70e5a131407b2/layouts/index.html#L75-L77

You may override this by copying the theme's template file into your site at `root/layouts/index.html` and removing lines 75 and 77.

Here's more on overriding template files: https://gohugobrasil.netlify.app/themes/customizing/#override-template-files

You're welcome, and I hope that helps!
