### ISSUE TITLE
Page is not responding/scrolling when clicking back from individual project

### ISSUE THREAD

**Issue by ParagRaut** [victoriadrake/hugo-theme-introduction#253]
**Describe the bug**

**To Reproduce**
When you have more than 3 projects, you seee option to see All Projects

you click on that > you see individual projects > you click on project > you click back on browser > page is unable to scroll

**Expected behavior**
After clicking back page should be interactable and scrollable

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome & Safari
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 11 Max Pro
 - OS: [e.g. iOS8.1] iOS 14
 - Browser [e.g. stock browser, safari] Safari & Chrome
 - Version [e.g. 22] latest

**Additional context**

**Comment by ParagRaut** [comment]
It happens when you quickly try to interact with web page before it finished loading. So marking it as false positive and closing it

**Comment by ParagRaut** [comment]
After little more investigation I found out if viewport is at 100% then it is still unresponsive, only after you pinch to zoom a little it becomes responsive again

**Comment by jakemanderson** [comment]
Try modifying the overflow property in the assets folder via

`sed -i -- 's/overflow: hidden/overflow: scroll/g' **/*(D.)`
