### ISSUE TITLE
The navbar-burger button not working

### ISSUE THREAD

**Issue by Eclectikus** [victoriadrake/hugo-theme-introduction#259]
**Describe the bug:**

`navbar-burger` button not working

**To Reproduce:**

1. Go to the homepage <https://nosolodatos.netlify.app/> from a mobile device or alternatively, click `F12` and use the mobile device emulator
2. Click on `navbar-burger` button

**Expected behavior:**

The navigation menu is shown

**Actual behavior:**

The navigation menu is not shown, nothing happens

**Screenshots:**

NA

**Desktop:**

- OS: Windows 10
- Browser [Chrome, Firefox, Brave, Edge, Opera]
- Version [Last versions]

**Smartphone:**

- Device: [Moto G5 Plus, Moto G2]
- OS: [Android 8.1.0, Android 6.0]
- Browser [Firefox, Chrome]
- Version [Last versions]

**Additional context:**

I use `Introduction` mostly for the front page (heavily customized though), and am not sure when this bug started to show up. Unfortunately it is not in a public repository, and just in case it could help I have shared the main config files:

- Custom CSS: [mystyle.css](https://gist.github.com/Eclectikus/5e54039dbaeec357dbc968aa6717366f)
- TOML: [config.toml](https://gist.github.com/Eclectikus/7f8c24f4576c44f2e0083f6ccdd0cb16)

**Comment by ParagRaut** [comment]
Before putting an issue, can you please check once if vanilla theme (eg. example site) renders correctly in both web and mobile view on your local ?

**Comment by Eclectikus** [comment]
Hi, actually I'm running [another site](https://buscosint.netlify.app/) with similar configuration and works as expected. It must be something specific but I have been unable to find the glitch. Thanks.

**Comment by ParagRaut** [comment]
Seems like checksum (integration) issue with scripts. When you load your site you can see that javascripts for your site are not loading. and that might be an issue as clicking hamburger needs to target navMenu.

Refer this:
<img width="825" alt="Screenshot 2020-11-13 at 21 28 57" src="https://user-images.githubusercontent.com/16030809/99118295-8f85ea00-25f7-11eb-9692-74cdefa3a184.png">


please rebuild site once on local and try deploying it again

**Comment by Eclectikus** [comment]
Thank you. I have been using `blogdown:::serve site()` all along and the bug hasn't disappeared. I will build the site (`blogdown::build_site()`) following [this guide](https://bookdown.org/yihui/blogdown/local-preview.html), and will let you know if it's worked. Thanks!

**Comment by ParagRaut** [comment]
Hope it works

**Comment by Eclectikus** [comment]
I have rebuild the site both via `blogdown:::serve site()` and from the CL (command `hugo`) with no avail. Something is wrong with my site, and it's probably my mistake rather than Hugo's or theme error. I leave the issue open in case someone has had the same problem or have any clue to fix it.

**Comment by victoriadrake** [comment]
Hello! I noticed this difference in your URLs may be causing the [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) error:

![Screenshot from 2020-11-14 15-39-16](https://user-images.githubusercontent.com/24644237/99156583-fb1b9600-268f-11eb-9ad9-ed71b5ae8059.png)

Perhaps you can update the URL of your site in your `config`.

If that is not a solution, we have had a few [issues with users using blogdown before](https://github.com/victoriadrake/hugo-theme-introduction/issues?q=is%3Aissue+is%3Aclosed+blogdown). Can you perhaps tell me if any of the information there is helpful to you?

**Comment by Eclectikus** [comment]
Hi @victoriadrake, YES! Quick and to the point, the URL's difference did cause this glitch, just changing TOML configuration fixed the error. Thanks SO MUCH!

**Comment by victoriadrake** [comment]
Glad to have helped! Enjoy the theme!
