### ISSUE TITLE
Help Appreciated :-) Remove frame/shadow around image

### ISSUE THREAD

**Issue by GITchristoph** [victoriadrake/hugo-theme-introduction#261]
Dear Viktoria

I have one question. I would be very grateful if you could help me with it, but obviously I know this is not your job.

How could I remove the shadow aorund the images (e.g. on the "About" section).
Please see below.

I found in the Google debug console that I probably have to change something for the "img-responsive avatar", but I have no idea which css I file I should edit. There are so many.

![image](https://user-images.githubusercontent.com/4885236/99152287-3377a000-26a1-11eb-81f0-9874cd818558.png)

**Comment by GITchristoph** [comment]
Hi

What I tried to do is to uncomment customCSS and to add the path to it:

![image](https://user-images.githubusercontent.com/4885236/99153821-37102480-26ab-11eb-8134-1f1c8e64fd60.png)

and then to add into assets/css/custom.css for .img-responsive that box-shadow: none:

![image](https://user-images.githubusercontent.com/4885236/99153830-560eb680-26ab-11eb-8000-57a3fdbe3220.png)

But this doesn't change anything.

(I have never done this before, I might be on the wrong track...)

**Comment by GITchristoph** [comment]
Ok, I sorted it.

I copied and pasted the complete sass files from the template to the custom css folders.

Then it works.

Juhuu!

**Comment by victoriadrake** [comment]
Glad you got it figured out! For the future, one probable reason your `custom.css` file didn't work is that you'd written with Sass syntax instead of CSS.

**Comment by GITchristoph** [comment]
@victoriadrake 
Thanks. To be honest I don't know the difference between sass and css.

May I ask out of curisoity how you write this part in css (instead of sass)?
Maybe based on that I can find an even better solution.

```
.img-responsive
   box-shadow: none  
```

**Comment by victoriadrake** [comment]
I believe [this explanation](https://stackoverflow.com/a/46400867) can help!

**Comment by GITchristoph** [comment]
Cool, thank you!

**Comment by GITchristoph** [comment]
What's strange is that when I deploy the side with `Hugo server -D` or with `-b https://test.mysite.com" and upload it to my server, then it does not take the custom css into account and the icon don't show.

It looks perfect when running the server with `hugo server -D` on my Macbook and accessing with http://localhost:1313

Could you imagine why ?

This might also be the solution for the "issue" that the icons don't show?

**Comment by victoriadrake** [comment]
Is there any console output? Could be a situation similar to #259 ?

**Comment by GITchristoph** [comment]
I checked again and the domain is correctly stated in the baseURL

`baseURL = "https://test.mysite.com/"`

So it shouldn't be connected.

Could it have to do with the icons not showing issue  (I opened that a bit earlier today)?

The icons are also not appearing on https://themes.gohugo.io/theme/hugo-theme-introduction/

**Comment by victoriadrake** [comment]
#260
