### ISSUE TITLE
Back to Projects is not showing up

### ISSUE THREAD

**Issue by MyGiHu** [victoriadrake/hugo-theme-introduction#262]
Back to Projects is not showing up. Looks like a typo in this line.

https://github.com/victoriadrake/hugo-theme-introduction/blob/32d46f19f436c02c83d1c81439fcad2901f0f038/layouts/partials/nav.html#L61

**Comment by victoriadrake** [comment]
Hi there! Would you be more specific about where you're not seeing it work? The link in the line you reference seems to show up fine on the demo page: https://hugo-introduction.netlify.app/projects/photography/

**Comment by ParagRaut** [comment]
I think he/she means following but in projects context

<img width="729" alt="Screenshot 2020-11-21 at 13 54 19" src="https://user-images.githubusercontent.com/16030809/99877820-273f9580-2c01-11eb-8989-5cd5d02dbbcc.png">


when user goes to a particular blog, theme shows option to go back to list of blogs "Back to blog", it doesn't happen in case of projects

@MyGiHu let me know if I'm correct

**Comment by MyGiHu** [comment]
@ParagRaut exactly

If you navigate to the site of a project (for exsample /projects/design/) the navigation bar should look like this:

![nav issue](https://user-images.githubusercontent.com/74786828/99882148-a394a180-2c1e-11eb-950b-0dc03460168c.PNG)

**Comment by victoriadrake** [comment]
That did it! Thank you for the PR @MyGiHu 😃
