### ISSUE TITLE
Disqus widget is not following content width

### ISSUE THREAD

**Issue by ParagRaut** [victoriadrake/hugo-theme-introduction#263]
**Describe the bug**
Disqus widget is taking whole width of page when seen in desktop browser

**To Reproduce**
1. Go to https://paragraut.me/projects/sideprojects/
2. Width of disqus widget looks out of proportion with respect to content

**Expected behavior**
Disqus widget should follow content width and justification

**Screenshots**
<img width="1599" alt="Screenshot 2020-11-21 at 13 51 07" src="https://user-images.githubusercontent.com/16030809/99877775-c44dfe80-2c00-11eb-8a9f-f28c73a89d67.png">

**Additional context**
@victoriadrake I understand that introduction theme is using Hugo's internal disqus widget but I don't know if similar issue has been posted before, can you suggest something ?

**Comment by MyGiHu** [comment]
There is no disqus class in the cascading style sheet and for me it looks like the width is defined by the css class container.

You can add container (for width) and top-pad (for some vertical space) to the disqus div to fix this issue.

**Comment by ParagRaut** [comment]
@MyGiHu Do you mean in theme itself or create a custom css ? if theme can you point me to correct file ?

**Comment by MyGiHu** [comment]
@ParagRaut In the theme itself. Here is the file and line: https://github.com/victoriadrake/hugo-theme-introduction/blob/696388d6bb228a7a3f6559e2e911469f8ac26a8f/layouts/partials/comments.html#L2
A custom css will fix it too, but adding existing css classes is easier.

**Comment by ParagRaut** [comment]
I'll try, and notify you if it worked. but don't you think it should be in default theme?

**Comment by MyGiHu** [comment]
I can only speculate why it is missing.

**Comment by ParagRaut** [comment]
@MyGiHu check https://github.com/victoriadrake/hugo-theme-introduction/pull/265 this worked for me on local

**Comment by MyGiHu** [comment]
Great!
