### ISSUE TITLE
clock has stopped

### ISSUE THREAD

**Issue by keen99** [victoriadrake/hugo-theme-introduction#273]
updated to latest today and I noticed the clock stopped working.

The code in this area seems to have been replaced as part of #266 (and stubbing in the old stuff doesnt work^H^Hcompile at a quick test)

My config seems intact, and at quick glance the required config didnt change....

ah there is an error on the js console:

```
**Uncaught RangeError: Incorrect locale information provided
    at Date.toLocaleTimeString (<anonymous>)
    at update_localtime ((index):544)
    at (index):547**
```
(line numbers may vary, I have local formatting changes)

my time config looks like:

```

        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "America/New_York"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "h:mm A"     
```

**Comment by keen99** [comment]
so it looks like the timeFormat changed:

https://github.com/victoriadrake/hugo-theme-introduction/pull/266/commits/7f720b4e1dadc7757e93c581c460c31f59d3df77#diff-a22ce72f559279e2b268c61544e9e67d3bec733d98c878c79ea381623539069cR26

`timeFormat               = "en-US"                 # Language specific format to use`

a bit of docu around this would be nice.   especially since this is a breaking change.

**Comment by victoriadrake** [comment]
Thanks for bringing that to my attention David! I've updated the docs and version.
