### ISSUE TITLE
ThemeStyle `auto` not detecting dark mode?

### ISSUE THREAD

**Issue by linhtto** [victoriadrake/hugo-theme-introduction#275]
**Describe the bug**
With the most recent update https://github.com/victoriadrake/hugo-theme-introduction/commit/2932037152a30e5542e947122ece0a26f148091b, `themeStyle` set to `auto` doesn't detect dark mode on my computer anymore.

**To Reproduce**
1. Use the included `exampleSite`
2. Make sure computer dark mode is on (MacOS 10.15.7)
3. Theme is light, not dark

**Expected behavior**
Theme should match computer dark mode.

**Desktop (please complete the following information):**
 - OS: MACOS 10.15.7
 - Browser: Chrome, Edge

**Comment by victoriadrake** [comment]
Thank you Linh! Pushed a fix.

**Comment by linhtto** [comment]
Thanks for the quick fix! I don't quite get it either, why the "drier" code doesn't work—if you ever find out, please let me know!

One thing though, the Github Actions tests didn't seem to pass?

**Comment by victoriadrake** [comment]
I noticed, even though it builds fine locally... 🤷 sorting that out now

**Comment by victoriadrake** [comment]
Seems to be coming from Bulma. I wonder if it's something that would be fixed by the update you started in #274?

https://github.com/victoriadrake/hugo-theme-introduction/runs/1633601928?check_suite_focus=true#step:6:7

**Comment by linhtto** [comment]
I doubt it. The bulma upgrade would just be from 0.9.0 to 0.9.1 and the changelog doesn't indicate anything likely to help.

**Comment by winxthecat** [comment]
I have the problem the other way round: I did setup the light mode and whilst MS Edge is following, Chrome / Safari are not.
