### ISSUE TITLE
local public folder does not render properly

### ISSUE THREAD

**Issue by dieterzakel** [victoriadrake/hugo-theme-introduction#276]
**Describe the bug**
the local public folder generated by hugo -D does not render properly
I guess something with absolute and relative URLs.

**To Reproduce**
1. generete site with host -D
2. open index HTML with browser - does not render
3. go to localhost:1313 - renders properly
4. See screenshots

**Expected behavior**
public folder should render properly

**Screenshots**
See

https://imgur.com/ROJMt9A
https://imgur.com/S1GeBqD
https://imgur.com/aoxJQkQ

<link rel="stylesheet" href="/css/main.min.5922d2d2157026d07c54911e0ff09089e5f7dce64e4457bd8cd9359da9a1722c.css" integrity="sha256-WSLS0hVwJtB8VJEeD/CQieX33OZORFe9jNk1namhciw=" crossorigin="anonymous" media="screen">

Not allowed to load local resource:
file:///css/main.min.5922d2d2157026d07c54911e0ff09089e5f7dce64e4457bd8cd9359da9a1722c.css

Thank you very much! 

**Desktop (please complete the following information):**
 - OS: macos 11.1
 - Browser Safari
 - Version 14.0.2

**Comment by MatthewMong** [comment]
Encountered same issue as well, my production builds are missing css too.

**Comment by MyGiHu** [comment]
Hugo and this theme are not optimized for local file access.
