### ISSUE TITLE
how to disable smooth scrolling to anchor links? aka make anchor links work twice++

### ISSUE THREAD

**Issue by keen99** [victoriadrake/hugo-theme-introduction#280]
Problem:  Anchor links only work on the 1st visit.   Reloading the page always takes you to the top.

Easy example, with the local server running, click an anchor link.   now edit something and watch it return to the top, even though the url is still /#anchor

This is symptomatic of the behavior of javascript's `scrollTo`, and probably others - but I'm not an expert in this area.

I'd like to be able to disable the smooth scrolling behavior (it's not something I care for anyway, regardless of breaking of anchors), but I can't figure out where in the theme this comes from.... 

If there's a flag to disable it already, excellent - if not, I'll either update my local copy, or submit a PR for such a flag if I can find a way to safely toggle it.

Can you offer any pointers?

thanks.

**Comment by victoriadrake** [comment]
We used to use `scrollTo`, but no longer do. You can update or override your Sass files to change the behavior here:

https://github.com/victoriadrake/hugo-theme-introduction/blob/2932037152a30e5542e947122ece0a26f148091b/assets/sass/_base.sass#L4-L5

I can't replicate your described behavior on the rendered demo site (https://hugo-introduction.netlify.com/). Does it only occur with live reload when using the Hugo server?

**Comment by keen99** [comment]
interesting, I can't repro on the demo either.

it's consistent across all of my stacks - local server, and netlify -
here's my prod environment where it's reproed:
https://www.brasstack.net/#about

so far I haven't been able to effect anything after changing my _base.sass
scroll-behavior, but I'll keep digging when I get a chance, thanks for the
pointer!
