### ISSUE TITLE
Update Font Awesome

### ISSUE THREAD

**Issue by mjdescy** [victoriadrake/hugo-theme-introduction#287]
I very much want to include [the "microblog" icon from Font Awesome 5.14.0](https://fontawesome.com/icons/microblog?style=brands) in my site's social icons. When I try to use it, using the code below in `config.toml`, nothing displays:

~~~
[[params.social]]
    url   = "https://user.micro.blog"
    icon  = "microblog" # icon name without the 'fa-'
    icon_pack = "fab"
~~~

Unfortunately, I don't know how to resolve this on my own. Does the Font Awesome code in the theme need to be updated? (I don't know how to do that.)

**Comment by MyGiHu** [comment]
You are right. Font Awesome is not up to date and is missing the microblog icon from newer releases.

**Comment by victoriadrake** [comment]
Font Awesome should be updated to include the "microblog' icon and other icons. Thank you @mjdescy for bringing this up!

**Comment by ttheng3810** [comment]
Hello, I would also like to point out that other than the "microblog" icon, the ["blog" icon from Font Awesome 5.6.0](https://fontawesome.com/icons/blog?style=solid) does not display on the site as well, after similar procedures as mentioned by @mjdescy are carried out.

The code used in the ```config.toml``` file:
```
[[params.social]]
    url   = "https://somebodys.blog"
    icon  = "blog" # icon name without the 'fa-'
    icon_pack = "fas"
```

**Comment by arturjzapater** [comment]
Hey, how's the progress on this? If no one is working on it, I'd be happy to do it (it might have to wait until the weekend, though)

**Comment by victoriadrake** [comment]
Please feel free, and thank you!

**Comment by arturjzapater** [comment]
Great!
