### ISSUE TITLE
Manual addition of icon packs other than Font Awesome, or extended support of other icon packs

### ISSUE THREAD

**Issue by ttheng3810** [victoriadrake/hugo-theme-introduction#291]
Hello, first of all, although I make this issue a feature request, this can actually be a problem report and a feature request at the same time.

I am happy with using this theme and am mostly satisfied with the Font Awesome icon pack included, except that the Font Awesome icon pack unfortunately does not provide the logo of a social network known as Plurk, which I would like to use as the icon representing one of my social links on the website. Hence, I decided to find another icon pack that includes that particular logo and then I eventually came across with this free icon pack on [Flaticon](https://www.flaticon.com/packs/social-logo-2).

Since I am still new in website building, I mainly relied on the instructions (which are in the local file **flaticon.html** after download) that are included after the download of the icon pack (which involves copying the corresponding font files and CSS files into the web source folder). At the same time, it is stated that this theme supports the addition of custom CSS files under the ```assets/ ``` folder, hence I copied the ```flaticon.css``` file which is included in the download pack into the ```assets/``` folder, and also edited the ```customCSS``` section of the ```config.toml``` file to the following:-
```customCSS = ["flaticon.css"]```

As for the icon, I edited the code related to social links (```[[params.social]]```) to this:-
```
url   = "https://plurk.com/"
icon  = "flaticon-069-plurk" 
icon_pack = "flaticon.css"
```

However, in the end, the icon still does not show up on the website and is emptied, but the others that use Font Awesome work normally.

Hence, I would like to ask how to manually add and apply the icons from icon packs other than Font Awesome, or is it possible to support the use of that particular icon pack, or even other more icon packs in the future? Thank you.

**Comment by MyGiHu** [comment]
If we take a look in [social.html](https://github.com/victoriadrake/hugo-theme-introduction/blob/34761ba2b22dd99c2b1bcf564bbf2777b7376a72/layouts/partials/home/social.html) we see all icons are starting with the prefix "fa-". Maybe your custom CSS file is missing this prefix.

Without changing the theme your custom CSS file could look like this:

```css
.fa-custom_icon_name:before {
    content: url(path to custom icon);
}
```
or something with `background-image: url(path to icon);` .

This solution **is not the prettiest way** and **requires some styling work**.
