### ISSUE TITLE
Some special characters cannot show up on the site title

### ISSUE THREAD

**Issue by ttheng3810** [victoriadrake/hugo-theme-introduction#293]
Hello again, I have come across with another problem when building my site using this theme which is about the site title.

I edited the site title by following the instructions written on the ```config.toml``` in the ```exampleSite``` folder.

I went through the usual steps which include copying the contents of the ```config.toml``` of the ```exampleSite``` folder into the ```config.toml``` in the site root, and changing the ```title``` variable in the file. I have changed the site title to what as shown below:
```
  title            = "Tze-Heng Tan  |  Welcome"
```

However, as a result, the special characters which I have typed within the quotation marks did not show up accordingly at the web browser, instead it appeared like this:
```Tze Heng Tan Welcome```
*(even the extra spacing is not shown)*

I have tried out other special characters like curly hyphen (~), hyphen (-) and colon (:), but they do not show up at the browser either.

Strangely enough, when I entered symbols like the single and double quotation marks (' "), and also the backtick (`), they *do* show up at the browser, but those symbols are not what I want to include in my site title.

May I know the reason behind this and how to resolve this issue? Thank you.

**Comment by ttheng3810** [comment]
Also, this problem only appears on the **homepage**; when the "sub-pages" are opened (e.g. the list page showing all of my blog posts), the special characters are shown normally instead, like this:
```Blog - Tze-Heng Tan | Welcome```

**Comment by MyGiHu** [comment]
The title ist generated by the [metadata.html](https://github.com/victoriadrake/hugo-theme-introduction/blob/34761ba2b22dd99c2b1bcf564bbf2777b7376a72/layouts/partials/head/metadata.html#L9) file.

As you can see the title ist put together with a ["Page Title"](https://gohugo.io/variables/page/) (title parameter from the markdown file) and a ["Site Title"](https://gohugo.io/variables/site/) (title parameter from the config.toml file) variable.

The title generating code line also contains text formating intstructions like [humanize](https://gohugo.io/functions/humanize/). So only your special characters in the "Page Title" variable are formated away by the humanize function.

On subpage level they are different variables. But on homepage level they have the same value - title parameter from the config.toml file. This leads to your described issue.

Removing the humanize function should fix your issue.
