### ISSUE TITLE
Fenced code block colour.

### ISSUE THREAD

**Issue by chris3ware** [victoriadrake/hugo-theme-introduction#294]
**Is your feature request related to a problem? Please describe.**
Fenced code blocks are displayed differently to code. Code appears to use $primary for text and $code-background for the background defined in _dark-variables.sass. However fenced code blocks are displayed with different colours.

**Describe the solution you'd like**
I'd like to be able to define a colour for fenced code blocks in _dark-variables.sass or fenced code blocks use $primary for text and $code-background the same way code does.

**Describe alternatives you've considered**
I've tried using code on multiple lines but have struggled to find a way to handle the indentation required. I'm trying represent a piece of YAML in a blog post.

**Additional context**
The following fenced code block in Markdown is displayed like this:  
<img width="269" alt="Screenshot 2021-04-02 at 21 52 34" src="https://user-images.githubusercontent.com/36608309/113453412-d127fd80-93fd-11eb-8ae3-7838c5d64ed5.png">  

<img width="265" alt="Screenshot 2021-04-02 at 21 55 12" src="https://user-images.githubusercontent.com/36608309/113453542-2106c480-93fe-11eb-99cd-22e56f43868a.png">

Code is displayed like this:

<img width="148" alt="Screenshot 2021-04-02 at 21 56 58" src="https://user-images.githubusercontent.com/36608309/113453859-d3d72280-93fe-11eb-8895-a843a0e2c8c3.png">

<img width="151" alt="Screenshot 2021-04-02 at 21 57 22" src="https://user-images.githubusercontent.com/36608309/113453916-ecdfd380-93fe-11eb-8248-34276f6244bc.png">

Thank you in advance for any support.

**Comment by MyGiHu** [comment]
Code is styled by the theme and fenced code blocks are styled by Hugo.

You can change the code theme under the markup options in the config.toml `style =  "name of style"`.

Or:

You can [create your own code theme](https://discourse.gohugo.io/t/unable-to-customize-the-syntax-highlight-colors/22140/2). 
Updated config lines: ` codeFences = true noClasses = false`

Or:

Set `codeFences = false` in config.toml and modify related sass files.

**Comment by chris3ware** [comment]
Perfect, thank you for the clear explanation. I copied the [markup] section from exampleSite/config.toml to mySite/config.toml, and have chosen the **style** as suggested. This is working as expected.

<img width="323" alt="Screenshot 2021-04-03 at 07 32 10" src="https://user-images.githubusercontent.com/36608309/113470603-c5185c00-944e-11eb-839c-5238ea7e27ed.png">
