### ISSUE TITLE
Add a toggle button for Dark/Light theme.

### ISSUE THREAD

**Issue by MisanthropicDeity** [victoriadrake/hugo-theme-introduction#299]
**Feature Description:**
A toggle button for light/dark theme so that users can switch between light and dark theme at any time.

**Solution Approach:**
A float.py button can be added in layout/partials which will have a toggle button to switch from light and dark theme.
And in javascript, we can write a function to toggle the dark mode on and off.

Thank you for such an amazing theme.

**Comment by victoriadrake** [comment]
Sounds great! Thank you!

**Comment by MisanthropicDeity** [comment]
Thank you, ma'am.
