### ISSUE TITLE
Modal won't switch to active on live website.

### ISSUE THREAD

**Issue by OLGJ** [victoriadrake/hugo-theme-introduction#303]
**Describe the bug**
Modal won't switch to active on live website.

**To Reproduce**
1. Go to 'https://www.olgj.org/'
2. Scroll down to 'Projects'
2. Click on either one of the projects

**Expected behavior**
Modal switches to active when a project is pressed (as it does on live preview with ```hugo serve```).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome [e.g. chrome, safari]
 - Version: hugo v0.84.0-2C4689F7B+extended windows/amd64 BuildDate=2021-06-18T17:14:27Z VendorInfo=gohugoio

**Additional context**
The functionality of the website works well when I do the preview with localhost. But on the live version clicking on projects does not result in modal class switching to active.

The repository which I've created the site with:
https://github.com/OLGJ/Website

**Comment by gthoma17** [comment]
This seems to be a problem with the configuration of your web server -- it isn't sending the CSS stylesheet that is needed to make the projects section work properly. 

I see this error in the Chrome Developer Console when I load up your website:

```
Access to CSS stylesheet at 'https://olgj.org/styles/owlCarousel.min.b1f26e29c43c61fe8b5a6f225b4ee7c5f969a7b33cfe512706271e07246d93d1.css' from origin 'https://www.olgj.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Try changing your server's CORS policy, that should fix it :+1:
