### ISSUE TITLE
Date format localisation issues

### ISSUE THREAD

**Issue by ttheng3810** [victoriadrake/hugo-theme-introduction#306]
Hello, I am planning to apply a Malay language month name (a language not included in the default theme repo) for the publishing date of the blog posts shown on my website.

How should I apply the steps provided on [this official Hugo documentation](https://gohugo.io/content-management/multilingual/#customize-dates), or can I?

I am aware that the lines of code in the single page template ([../blog/single.html](https://github.com/victoriadrake/hugo-theme-introduction/blob/master/layouts/blog/single.html)) controlling the date section is the following...
```
{{ if .Params.date }}{{ .Date.Format (.Site.Params.dateFormat | default "Jan 02, 2006") }} |{{ end }}
``` 
...and also the following lines found in [config.toml](https://github.com/victoriadrake/hugo-theme-introduction/blob/master/exampleSite/config.toml):
```
[params]
...
 dateFormat                   = "Jan 2, 2006"
...
[languages.de.params]
            dateFormat   = "2. January 2006"
            description  = "Beschreibung der Webseite"
... 
```
(only part of the relevant code is shown, but hope you can get the point)

Since the language I intend to include is not included in the default repo, I cannot change to my desired date format (month name) for the language by only changing the ```dateFormat``` section in the config.toml file.

Also, I have tried just copying the example codes provided in the Hugo Docs straight away with some modifications to suit my needs, but it does not work.

Do the lines of code need a major revamp so that I can apply *other* non-English month names? Are there any other workarounds other than what provided in the Hugo Docs webpage?

Thank you in advance!

**Comment by MyGiHu** [comment]
You have already all the information you need. A hard coded date format is the only disadvantage of this solution. Maybe a partial template with many replace commands brings flexibility.

My /blog/single.html:
```
    <div class="post-data">
        {{ if .Params.date }} {{ .Date.Day }} {{ index $.Site.Data.mois (printf "%d" .Date.Month) }} {{ .Date.Year }} |{{ end }}
        {{ i18n "blog_readingTime" .ReadingTime }}
    </div>
```
Path of mois.yaml:
`<theme root>/data/mois.yaml`

Works for me.

**Comment by ttheng3810** [comment]
Hmm, if I make use of your version of modified /blog/single.html code, how should I configure the ```dateFormat``` in config.toml so that the month name can show up on the webpage?

**Comment by MyGiHu** [comment]
`dateFormat` is not evaluated by the modification. So no configuration of `dateFormat` is required.

Please note, this modification only affects the "full post site" and no other site like startpage or "list of all posts".

**Comment by ttheng3810** [comment]
I have discovered the error in my code, turns out that I have carelessly typed the filename of the data file wrong 😅. Now the month name can show up on my webpage after fixing that.

Thank you for your help!
