### ISSUE TITLE
Failed to process shortcode

### ISSUE THREAD

**Issue by Pirshtuk** [victoriadrake/hugo-theme-introduction#308]
Failed to build the site from template:

Start building sites … 
hugo v0.86.0-41C6C52E+extended windows/amd64 BuildDate=2021-07-21T09:53:14Z VendorInfo=gohugoio

Error: Error building site: "C:\Users\.....\Site-hugo-theme-introduction\content\en\blog\configuration.md:19:1": failed to render shortcode "md": failed to process shortcode: "C:\Users\......\Site-hugo-theme-introduction\layouts\shortcodes\readfile.html:7:12": execute of template failed: template: shortcodes/readfile.html:7:12: executing "shortcodes/readfile.html" at <readFile>: error calling readFile: CreateFile C:\Users\.....\Site-hugo-theme-introduction\config.toml: The system cannot find the file specified.

**Comment by victoriadrake** [comment]
Hi there. Hugo's trying to render the content in `\Site-hugo-theme-introduction\content\en\blog\configuration.md` and looking for [this file](https://github.com/victoriadrake/hugo-theme-introduction/blob/34761ba2b22dd99c2b1bcf564bbf2777b7376a72/exampleSite/layouts/shortcodes/readfile.html) which is housed in the `exampleSite` directory.

If you've deleted or moved `readfile.html` but you're still trying to render the content that asks for it, the [shortcode ](https://gohugo.io/content-management/shortcodes/) will not work.

This quick search can show you where the pieces are: https://github.com/victoriadrake/hugo-theme-introduction/search?q=readfile

Let us know if that helps!
