### ISSUE TITLE
Code snippets not enough contrast

### ISSUE THREAD

**Issue by christian-heusel** [victoriadrake/hugo-theme-introduction#310]
**Describe the bug**
I just now realized that one can barely read code snippets with this theme 😢 
Since I'll probably need them for future posts it would be awesome if this improves ❤️ 

**To Reproduce**
1. Go to [https://christian.heusel.eu/blog/minio/](https://christian.heusel.eu/blog/minio/)
2. Try to read the codesnippets

**Expected behavior**
One is easily able to read code blocks of any type.

**Screenshots**
![image](https://user-images.githubusercontent.com/26827864/145905345-25271f9e-706b-469a-9957-56f63a410ff1.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 95.0-1

**Smartphone (please complete the following information):**
 -

**Additional context**

**Comment by victoriadrake** [comment]
Hello Christian,

The syntax highlight colors can be controlled by your settings in your configuration file. In this case, the color scheme chosen does not work well with the light theme. I will try to find a better default.

In the meantime, you may change the color scheme setting to your liking. See the [configuration post](https://hugo-introduction.netlify.app/blog/configuration/) for more details.

I hope this is helpful!

**Comment by christian-heusel** [comment]
Hey @victoriadrake, awesome, I wasnt aware that I can configure this and also the new versions default fixes the problem 😊 
Thanks a lot for all your work 😄

**Comment by victoriadrake** [comment]
You're welcome!
