### ISSUE TITLE
Add Privacy Policy Page

### ISSUE THREAD

**Issue by chris-short** [victoriadrake/hugo-theme-introduction#311]
**Is your feature request related to a problem? Please describe.**
I would like to add a Privacy Policy page to the site but I'm not sure what the right/best way is.

**Describe the solution you'd like**
This should be a default option on sites incorporating Google Analytics especially. But, I really want to solve the "where should terms, policies, etc. go?"

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by winxthecat** [comment]
I also would like to know how to do that the best way.

**Comment by winxthecat** [comment]
I found a way:

Create a new section for the Home page - I named it Impressum (or imprint) and in that document use these HTML5 Options:

<details>
    <summary>

        ### Eine Überschrift

    </summary>
    <div>

        Test **mit Markdown**.

    </div>
</details>

So now visitors can access those pages directly on the front page, without having the hassle of the long legal blabla to be visible upfront. I combined my imprint and the data protection pages into one document. 

`---
title: "Impressum & Datenschutz"
weight: 90
---
**Impressum** 
<details>
    <summary>
Hier findet man mein Impressum mit den notwendigen Angaben
    </summary>
**Angaben gemäß § 5 TMG** 

</details>

**Datenschutz** 

<details>
    <summary>
Hier findet man mein Impressum mit den notwendigen Angaben
    </summary>
** 1. Datenschutz auf einen Blick** 
***Allgemeine Hinweise***
Die folgenden Hinweise geben einen einfachen &Uuml;berblick dar&uuml;ber, was mit Ihren personenbezogenen Daten 
</details>
`

(I deleted the text itself in the code section for my answer here at git)

**Comment by winxthecat** [comment]
[imprintgit.md](https://github.com/victoriadrake/hugo-theme-introduction/files/7986320/imprintgit.md)
