### ISSUE TITLE
Basic Problems 

### ISSUE THREAD

**Issue by C4E5G3** [victoriadrake/hugo-theme-introduction#312]
I am following the steps. I copy the config.toml file from the Example Site into the main site. I then create an index.md file in my main site.

Marcus@mx:~/WEBSITE/A/content/home
$ cp ~/WEBSITE/A/themes/introduction/exampleSite/content/en/home/index.md ~/WEBSITE/A/content/home

But the original Homepage does not render:- see below.

![hugo1313](https://user-images.githubusercontent.com/95769626/147611279-5fd0b0f4-041e-48cb-9f5a-c778dbd02df2.png)

**Comment by C4E5G3** [comment]
I haven't done this stuff for about 10  years, hence the elementary questions. My config says:


> [languages]
>     [languages.en]
>         languageName     = "English"
>         languageCode     = "en-us"
>         contentDir       = "content/en"

So I am thinking my directory has to be main/content/en/home

But that doesn't work either....

**Comment by C4E5G3** [comment]
Okay, I solved this myself.....I use the verb 'solve' generously.

I just copied exampleSite/* to my main site, and it was Happy Days.

**Comment by victoriadrake** [comment]
Hello Marcus! Glad you got it figured out. For your future reference, Hugo is quite sensitive to the [file structure](https://gohugo.io/content-management/organization/). I don't know what it was before you worked off a copy of exampleSite, but that may have been the issue.

Have fun with your website!

**Comment by C4E5G3** [comment]
Hi Victoria,
Yes, I am just working it out. I am out of the loop. I stuck up a static
site about 5 years ago, on Dropbox, but the world looks different now.
I have to say, your Theme is stellar, Je le kiffe, as we say in France.
I am really looking forward to getting something "set in the cloud".

Bravo!!! You are an artist.

Best Regards
Marcus
