### ISSUE TITLE
Question: Display Markdown Images (badges) side by side

### ISSUE THREAD

**Issue by RobinMaas95** [victoriadrake/hugo-theme-introduction#313]
If I use the following code in a file inside the `content/en/home` folder, all badges are displayed one below the other.
When I use the same code in other locations (e.g., my personal GitHub page or here), the badges are rendered side-by-side.

Is there a way to force `Introduction` to render them side-by-side, too?

Code:
```markdown
#### Languages
![Python](https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54)![Swift](https://img.shields.io/badge/swift-F54A2A?style=for-the-badge&logo=swift&logoColor=white)![Java](https://img.shields.io/badge/java-%23ED8B00.svg?style=for-the-badge&logo=java&logoColor=white)![Markdown](https://img.shields.io/badge/markdown-%23000000.svg?style=for-the-badge&logo=markdown&logoColor=white)![LaTeX](https://img.shields.io/badge/latex-%23008080.svg?style=for-the-badge&logo=latex&logoColor=white)
```

Expected behavior:
#### Languages
![Python](https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54)![Swift](https://img.shields.io/badge/swift-F54A2A?style=for-the-badge&logo=swift&logoColor=white)![Java](https://img.shields.io/badge/java-%23ED8B00.svg?style=for-the-badge&logo=java&logoColor=white)![Markdown](https://img.shields.io/badge/markdown-%23000000.svg?style=for-the-badge&logo=markdown&logoColor=white)![LaTeX](https://img.shields.io/badge/latex-%23008080.svg?style=for-the-badge&logo=latex&logoColor=white)

Current behaviour:
<img width="852" alt="hugo_issue" src="https://user-images.githubusercontent.com/38866594/147709026-ff635232-ea4b-4c51-bbb2-407ee8012363.png">

**Comment by victoriadrake** [comment]
Hello! This happens because the Markdown CSS renders each badge image by itself on a new line with padding. It's controlled by these Sass lines:

https://github.com/RobinMaas95/hugo-theme-introduction/blob/2dd728c9fd921da23a3fce79acce24d50d0e5e7f/assets/sass/_base.sass#L290-L293

You can change or remove this Sass code in your fork to have the badges render as they do on GitHub in READMEs. Hope that helps!
