### ISSUE TITLE
A Guide

### ISSUE THREAD

**Issue by OnPointSM** [victoriadrake/hugo-theme-introduction#314]
This theme is really excellent, and I think Victoria deserves kudos for making it. Coming from Wordpress, and not having dabbled in code for many years, I am struggling to adapt it though. 

In one sense it would be good if someone wrote a basic guide to some of the adaption process, e.g. I can't understand the relation of the theme files to the main site, and even though I've copied the them into my main site, the i18 folder only exists in the theme. In fact there is a whole lot I don't understand.....

Of course, the downside is that a guide would popularize the theme....

**Comment by OnPointSM** [comment]
If I try and call French as my language, (from config.toml):

DefaultContentLanguage           = "fr"                    # Default language for multilingual sites
.............
[languages]
        [languages.en]
            languageName     = "Français"
            languageCode     = "fr"

I get this in the CLI:

Error: site config value "fr" for defaultContentLanguage does not match any language definition

**Comment by OnPointSM** [comment]
[languages]
[languages.fr]

modified, but still renders an error. Hmmm.

**Comment by OnPointSM** [comment]
Apologies...sorted

**Comment by winxthecat** [comment]
I just wanted to drop a note, expressing how much I love this theme.

I was looking for a German website to replace my old one with Hugo/Hermit (no longer updated) and this was so easy! Just change the main language in config, delete the other languages (although I might keep the English version and FINALLY have a bilingual website), upload and done. 

What I did was: move the example content into my website root, so the page works extremely well.

**Comment by OnPointSM** [comment]
Yes, I had to create a French folder in content, and then just mimicked the en folder. 
And i deleted the other languages in the config file and created a French one.
Just a matter of tinkering really.

**Comment by OnPointSM** [comment]
Thanks
