### ISSUE TITLE
Footer editable

### ISSUE THREAD

**Issue by winxthecat** [victoriadrake/hugo-theme-introduction#318]
**Is your feature request related to a problem? Please describe.**
The great theme has the option to override the footer info. But I do not like to remove credits, especially for any open source stuff. 

I would rather like to change it a bit. I want to leave the links and text as it is, just simply create something like this:
**&copy my name (actual year) | your footer text**

Any idea, how I can do that? 

(on my old webseite www.beck24.be I just did that)

**Comment by winxthecat** [comment]
I did try to use the icons from FontAwesome, but I did not get them to work. No matter, what I tried, hugo always came back with: 

> /config.toml:120:184: unmarshal failed: toml: expected newline but got U+0066 'f' 

The footer works (in Edge) without icons, but somehow, I feel like it misses something.

**Comment by winxthecat** [comment]
Hi, would that footer be OK for you @victoriadrake ? 
© Volker Beck 2022 | Erstellt mit [hugo](https://gohugo.io/) und dem Theme [Introduction](https://github.com/victoriadrake/hugo-theme-introduction/). 

roughly translated as Volker Beck | generated with Hugo and the theme introduction. 

Or would you prefer to also have a link to your general website? 

- I am still working on my German site -

**Comment by winxthecat** [comment]
Hi, would that footer be OK for you @victoriadrake ? 
© Volker Beck 2022 | Erstellt mit [hugo](https://gohugo.io/) und dem Theme [Introduction](https://github.com/victoriadrake/hugo-theme-introduction/). 

roughly translated as Volker Beck | generated with Hugo and the theme introduction. 

- I am still working on my German site, so there is no finished English version of the footer - 

I will close this issue. Please reopen it, if you would like me to use another footer or include the link to your general website as well.

**Comment by victoriadrake** [comment]
Thank you for asking, Volker! It's very considerate of you. I appreciate you wanting to leave the credit in and your suggestion looks great!
