### ISSUE TITLE
Weird Date Format

### ISSUE THREAD

**Issue by winxthecat** [victoriadrake/hugo-theme-introduction#319]
**Describe the bug**
I created a blog post, using the date format from the Hipster-Ipsum. (date: 2017-11-13T11:58:39-05:00). it works well in English. However, as soon as I upload the identical file into the German version, the date ALWAYS gets changed into January. That change happens to the demo content as well as my newly created blog post. 

My date: 
date: 2021-11-15T12:00:00-05:00
EN: Nov 15, 2021 | 1 minute read 
DE: 15. Januar 2021 | 1 Minute zum Lesen 

I use this format (like the one in the example page) in config.toml:
    dateFormat                   = "Jan 2, 2006"

Any idea why it does that?

**Comment by victoriadrake** [comment]
Hello!

Is there a separate line controlling date format in your configuration under the German language settings?

https://github.com/victoriadrake/hugo-theme-introduction/blob/2dd728c9fd921da23a3fce79acce24d50d0e5e7f/exampleSite/config.toml#L139-L140

The format here may be incorrect.

**Comment by winxthecat** [comment]
Yeah, that was it. Thx a lot! I will close the issue.
