### ISSUE TITLE
Footer text

### ISSUE THREAD

**Issue by OnPointSM** [victoriadrake/hugo-theme-introduction#320]
Has anyone succesfully added a  customer service chatbox? i am trying to get crisp working, but no luck so far.

Edit: moved to #321

**Comment by OnPointSM** [comment]
Not being funny , but I really don't understand the logic of the build, and whether Introduction is a typical hugo build or not. E.G. I adapted the footer text, primarily to create a new target link that opens independently, but my website reverts to the original footer text. However when I search my file structure for "contributeurs open-source" as appears on my live website, this text does not appear, and only appears in the unabridged themes/introduction/i118/fr.toml file. 

I am just an old school bodger who used to tinker with WP may years back. Maybe I am out of place here, and need to revert to a more simple site builder, I don't know. Even basic science such as locating the header eludes me.

**Comment by OnPointSM** [comment]
Ah! Thanks Victoria. I inadvertently erased that line when modifying the language settings. Thank you for your advice, it is very helpful. I simply reformulated the footer that is all, with a link that opens in a new browser. The link comes up blue actually.

Text   = '<p>Thanks to Victoria @<a href="https://github.com/victoriadrake/hugo-theme-introduction/" target="_blank" >Introduction Theme</a>.</p>'                      #

**Comment by victoriadrake** [comment]
Great! I’m glad it worked out 😁
