### ISSUE TITLE
Language Sites

### ISSUE THREAD

**Issue by OnPointSM** [victoriadrake/hugo-theme-introduction#323]
I am wondering if it is me being dense, or whether co-opting the theme for a foreign language site is not really practicable.
I have made a monolingual site, in French, so the other languages are now inactive.

My main index.html in docs is of this type:

```
<html lang="en-us">

    <head>
	<meta name="generator" content="Hugo 0.74.2" />
        <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="chrome=1">

.....etc
```

(docs/de) German and (docs/fr) Spanish are similar, just the language is adapted.

(docs/en) is like this 

```
< !DOCTYPE html><html><head><title>http://example.com/</title><link rel="canonical" href="http://example.com/"/><meta name="robots" content="noindex"><meta charset="utf-8" /><meta http-equiv="refresh" content="0; url=http://example.com/" /></head></html>

{{ $paginator := .Paginate (where .Site.RegularPages ".Params.post" "!=" false) }}

{{ if .IsHome }}
  {{ if eq $paginator.PageNumber 1 }}
    <title>{{ .Title }}</title>
    <meta name="description" content="{{ .Site.Params.description }}" />
  {{ else }}
    <title>{{ .Title }} | Page {{ $paginator.PageNumber }}</title>
    <meta name="description" content="This is page {{ $paginator.PageNumber }} of our content." />
  {{ end }}
{{ else }}
  {{ if .Params.seoTitle }}
    <title>{{ .Params.seoTitle }}</title>
  {{ else }}
    <title>{{ .Title }}</title>
  {{ end }}
  <meta name="description" content="{{ .Description }}" / >
{{ end}}
```

And the docs/fr is thus:

`<!DOCTYPE html><html><head><title>https://www.onpointsm.fr/</title><link rel="canonical" href="https://www.onpointsm.fr/"/><meta name="robots" content="noindex"><meta charset="utf-8" /><meta http-equiv="refresh" content="0; url=https://www.onpointsm.fr/" /></head></html>`

So I am wondering why my docs/fr/index.html is so sparse....

Do i need to modify or add something?

**Comment by OnPointSM** [comment]
Nice.....but your portfolio does not open

**Comment by OnPointSM** [comment]
And obviously, like me, you are a work in progress

https://volkerbeck.info/en/

**Comment by winxthecat** [comment]
Strange, I was able to open them in English (not yet finished) and German:

https://volkerbeck.info/en/#projects 

https://volkerbeck.info/projects/ - works well
