### ISSUE TITLE
Cookie Consent?

### ISSUE THREAD

**Issue by winxthecat** [victoriadrake/hugo-theme-introduction#325]
**Is your feature request related to a problem? Please describe.**
In Germany/Europe, the data protection is an important thing for any website and there are specialized lawyers just searching for websites that are not following protocoll and serving notices to those websites.

As I understand, introduction uses google fonts, right? And I am also using fontawesome. Both is OK for me as I integrated them in my data protection info.  

**Describe the solution you'd like**
A cookie consent would be great. Just a simple "please allow cookies" and the option to deny that. Would that be possible? 

I searched hugo's website and found no information how to do that.

**Comment by winxthecat** [comment]
There is this solution: https://hugocodex.org/add-ons/cookie-consent/

but it only revolves around google analytics and some chat function. Not the use of google fonts/font awesome.

**Comment by victoriadrake** [comment]
Looking at the **Installation** section of the link you added, it seems that you can modify the language in the YAML file to cover Google Fonts. Would that work?
