### ISSUE TITLE
Titles Colour 

### ISSUE THREAD

**Issue by OnPointSM** [victoriadrake/hugo-theme-introduction#330]
How do you change the light blue colour of the icons and titles?

**Comment by jonathf** [comment]
I was wondering the same thing, so I starting diging through the theme code. I found the theme's colors defined in the folder `assets/sass/_{dark,light}-variables.sass`.

The color you want to change is `primary`.

**Comment by OnPointSM** [comment]
Ah, thanks Jonathon, that is terrific
