### ISSUE TITLE
Site still using example.org for owlCarousel asset

### ISSUE THREAD

**Issue by ChaosParadise** [victoriadrake/hugo-theme-introduction#331]
**Describe the bug**
After running a production build of a site using this team, some example CSS files are trying to be included.

```
“https://example.org/js/bundle.5c23c0437f001a469ca373a465a6f7487203d18e10cdff76d86a60af66d5ee28.js” is not eligible for integrity checks since it’s neither CORS-enabled nor same-origin.
“https://example.org/js/bundleOwlCarousel.bc6b73f0a36bf19c70c5df8fc352d322988ca2bc40743fb836ee7371d555c28a.js” is not eligible for integrity checks since it’s neither CORS-enabled nor same-origin
```

**To Reproduce**
Follow the basic setup instructions in the README. I also added a custom.css file to the config which loads in fine.

**Expected behavior**
It should use a bundled owlCarousel

**Additional context**

**Comment by braunsonm** [comment]
Bump.

**Comment by ChaosParadise** [comment]
Bump

**Comment by ChaosParadise** [comment]
@victoriadrake Can you reopen this?
