### ISSUE TITLE
Icon Link Target

### ISSUE THREAD

**Issue by OnPointSM** [victoriadrake/hugo-theme-introduction#333]
I can't seem to find a workaround to make the social media icons open in a new target window.
Any ideas?

I did try creating a docs/js file

`jQuery(document.links)   .filter(function() {     return this.hostname != window.location.hostname;   })     .attr('target', '_blank');`

But this is not the solution.....

**Comment by OnPointSM** [comment]
I'm just saying.....

I have the impressionthat you've  designed the theme with SEO in mind Victoria, because sometimes on Lighthouse I get 100% X 4
And with one pathetically scrappy minimilist page, I am ranking top for my metathingy

But the target links (opening in the same browser window) for the icons will destroy a site's credibility, because time spent on the page will be reduced.

**Comment by victoriadrake** [comment]
You can use the additional `html_attributes` parameter in the config to do this.

See https://github.com/victoriadrake/hugo-theme-introduction/issues/324#issuecomment-1039027806
