### ISSUE TITLE
Hamburger menu dark mode background not changing.

### ISSUE THREAD

**Issue by L-Steinmacher** [victoriadrake/hugo-theme-introduction#337]
**Describe the bug**
The Hamburger menu background doesn't change when in dark mode yet the text color does change making reading the links an impossible task. I've tested on multiple browsers and the same issue.

**To Reproduce**
1. Go to Hamburger Menu in DarkMode
2. Click on it
3. Scroll down to  look at the open nav menu from hamburger
4. See White Box with no apparent links.

**Expected behavior**
Hamburger menu, when opened on Dark mode will appear as a white box with no apparent text.  Links are active and you can click them. 

**Screenshots**
![Screen Shot 2022-06-06 at 10 25 52 AM](https://user-images.githubusercontent.com/72778251/172214920-87fdb819-ea99-44b3-998f-7154dc57c056.png)

![Screen Shot 2022-06-06 at 10 25 41 AM](https://user-images.githubusercontent.com/72778251/172214965-3f7ff796-3043-485b-afbe-a945a9803b20.png)

**Desktop (please complete the following information):**
 - OS: MacOs 10.15.7
 - Browser: Chrome, brave
 - Version: 102.0.5005.61

**Smartphone (please complete the following information):**
 - Device: Pixel 6/ One+ 9
 - OS: latest
 - Browser chrome/ brave/ Vivaldi
 - Version latest

**Additional context**
No additional context is needed I believe.  I love this theme and your work!

**Comment by mhutchinson** [comment]
I have a fix for this in #347
