### ISSUE TITLE
Accommodate the new Google Analytics 4

### ISSUE THREAD

**Issue by linhtto** [victoriadrake/hugo-theme-introduction#338]
**Is your feature request related to a problem? Please describe.**
The current footnote script accommodates Google Analytics 3 (Universal Analytics) but not the new Google Analytics 4. Google will no longer support Universal Analytics in 2023.

See [here](https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/).

**Describe the solution you'd like**
- Hugo already takes care of this upstream https://gohugo.io/templates/internal/#google-analytics
- The only change needed is to call `{{ template "_internal/google_analytics.html" . }}` instead of `{{ template "_internal/google_analytics_async.html" . }}` inside `/layouts/partials/footer/scripts.html`. This solution will accommodate both versions of Google Analytics ("G-" IDs will be recognized as GA4, and "UA-" IDs as GA3. 

Please let me know if you want me to go ahead and make this change.

**Comment by linhtto** [comment]
Relatedly, Google Analytics' own instructions say to put the script into the Head section ("Copy the global site tag into the <head> section of your HTML.") but right now the theme adds it in the Body section. Should this be changed?

**Comment by victoriadrake** [comment]
Sounds good! Please feel free to open a PR for this.

**Comment by kylecordes** [comment]
This might be stale, it is needed **more** not less because time has passed.
