### ISSUE TITLE
CV icon from academicons as a social icon

### ISSUE THREAD

**Issue by emgilfuster** [victoriadrake/hugo-theme-introduction#343]
I'm trying to use the CV icon from [academicons](https://jpswalsh.github.io/academicons/), specifically for the social icons in the header.
I've tried following their installation guide, but I don't know enough about Hugo/this theme (which I really like)/the markdown under-the-hood magic to make it work.

My dream solution would be a guide of what I need to do (e.g. where to add the elements I downloaded from the academicons page) so that in my `config.toml` I only need to write
```    
[[params.social]]
    url = "/files/cv.pdf"
    icon = "cv"
    icon_pack = "ai"
```
much the same way what I did for all the other icons using font-awesome.

I want mainly the cv icon, so any simpler solutions to get that single one would also make me very happy.
Some people on the internet mention ways to access the academicons icon pack directly from a URL without having to download anything, I have no idea if that's easier or more difficult, but in any case I'd be happy with either solution.

For context, I'm a phd student trying to get an elegant and simple personal webpage: [eliesgilfuster.eu](eliesgilfuster.eu).
I have little knowledge of html and css (maybe the equivalent of 5h of learning?)
All my hugo knowledge (and the introduction theme) reduces to the minimum necessary to get my page to its current state.
I'm quite confident with markdown.
I'll be very glad for any help on this front, but just wanted to let it be known that I'll probably not understand any jargon or other tricks of the trade.

Thanks so much in advance!

**Comment by bpkleer** [comment]
Hey there, 

since I also like this feature, I implemented academicons. I created a pull request, and once it might be accepted, you can easily choose **academicons** by indicating *icon_pack = "ai"*.

Best,
Phil

**Comment by emgilfuster** [comment]
Hi!
Thanks for taking the time to implement this :)
I've downloaded the files from your fork and replaced everything, but still when I write:
```
[[params.social]]
    url = "/files/cv.pdf"
    icon = "cv"
    icon_pack = "ai"
```
no icon shows up on the website.

Have I done something wrong? :)

Thanks!

**Comment by bpkleer** [comment]
Hey @emgilfuster,

from your lines I can just guess where a problem might be. 

1) Have you downloaded also the assets?

2) Is the path to the file correct?

I used this feature with html-links and it works perfectly (you can see at https://bpkleer.de)

**Comment by bpkleer** [comment]
Hey @emgilfuster,

from your lines I can just guess where a problem might be. 

1) Have you downloaded also the assets?

2) Is the path to the file correct?

I used this feature with html-links and it works perfectly (you can see at https://bpkleer.de)

**Comment by emgilfuster** [comment]
Hi @bpkleer,

Sorry for taking so long again.
I did also download the assets, I just downloaded your entire fork 😅 
I'm not sure if with path to the file you mean my cv.pdf file, or somehow the path to the icon file in the assets jungle.

The path to the file is correct.
I know it is because when I write
```
    [[params.social]]
        url = "/files/Gil-Fuster.pdf"
        icon = "route"
        icon_pack = "fas"
```
I get no icon but I can still click on the empty space and it takes me to the right link.

In case you meant some more obscure ai-related files, then I guess I don't know enough to say anything meaningful.
I'm very thankful for the time you've spent already, and I'll keep trying to solve this myself.
But just in case, I made my repository public:
https://github.com/emgilfuster/eliesgilfuster.eu
Maybe there's some stupid mistake that I made and that's also easy to catch?

This is my [`config.toml` file](https://github.com/emgilfuster/eliesgilfuster.eu/blob/main/config.toml), the relevant lines are 68 to 71.
It might be I haven't been using the fact that `themes/introduction` is a submodule and should be treated as such 🤔 so changes I make on `themes/introduction/assets` might not be reflected somewhere sensitive?

Anyway, thanks so much for your help!
Cheers Elies
Cheers Elies

**Comment by bpkleer** [comment]
Hey @emgilfuster,

unfortunately I don't have time to take a look at your repository. But your hint might leading in the correct direction: You need to change the assets in the themes-folders resp. add my files there (that's how I did it) and it worked for me.

**Comment by victoriadrake** [comment]
Hello Elies!

Can you see if this issue persists now that #344 is merged?
