### ISSUE TITLE
Light theme on mobile (Android) not working

### ISSUE THREAD

**Issue by andzoff** [victoriadrake/hugo-theme-introduction#366]
Hi Victoria, congratulations for the Introduction hugo theme, it's very nice.
I'm using it on my site https://scuoladijava.it
My name is Andrea and I am an Italian IT specialist.

The main bug I'm facing with using Introduction is the dark/light theme on Android, that seems to not work.
For my site I don't want auto dark/light theme, I want only light theme ('cause I really don't like dark theme's colours).
So I selected _light_ theme on the _config.tolm_ file.

On Chrome browser on a notebook, everything seems to be OK, but on Android, for which I have the dark theme for the system, my site appears dark (as the system) and not light as I selected.
Have you got any suggestion for this issue?
Thanks.

**Comment by mansoorbarri** [comment]
have you tried clearing cache?

**Comment by andzoff** [comment]
Hi mansoorbarry,
now it works, maybe something was wrong in my installation, I re-installed my site.
Thanks for your support, the issue can be closed.
