### ISSUE TITLE
Top menu button not working on mobile (Android)

### ISSUE THREAD

**Issue by andzoff** [victoriadrake/hugo-theme-introduction#367]
Hi,
another problem I'm facing with, is the top menu button in Android.

On my Android mobile device,the top menu is not shown and is replaced bu a _three dashes_ button.
This is what happens commonly in mobile sites.
But when I tap the button, nothing happens, so I am not able to navigate the site.

Have you got any suggestion?
Thanks.

**Comment by mansoorbarri** [comment]
can't reproduce, seems to work on my device. Can you share your website or the source code? 

my device:
![Screenshot_20240421_014623_Firefox.jpg](https://github.com/victoriadrake/hugo-theme-introduction/assets/90044118/88529110-a044-4821-af39-4c5aa8be522d)
